version: '3.1'

services:

  game_of_life_telegram_bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: game_of_life_telegram_bot
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./:/app
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
