services:

  game_of_life_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: game_of_life_api
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"