services:

  game_of_life_api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WORKERS: ${WORKERS}
        PORT: ${PORT}
    image: game_of_life_api
    restart: unless-stopped
    env_file: .env
    environment:
      - PORT=5000
      - WORKERS=1
    volumes:
      - ./:/app
    ports:
      - "${PORT}:${PORT}"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"